#%RAML 1.0
title: hello

/hello:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message": "this is sample response from sample endpoint"
              }